sudo: required

branches:
  only:
  - travis

cache:
  directories:
  - .ccache
  - blender-addons-contrib.git
  - blender-addons.git
  - blender-dev-tools.git
  - blender-translations.git
  - blender

services:
- docker

arch:
  repos:
  - bartus=https://github.com/bartoszek/AUR-repo/raw/master
  packages:
  - ccache
  - moreutils
  script:
  - "echo 'options+=(ccache)' >> PKGBUILD"
  - "export CCACHE_DIR='/build/.ccache'"
#    COMPRESSXZ=(), can't be passed to makepkg as bash dosn't support array in `export` statement.
  - "sed '1i COMPRESSXZ=(xz -T 0 -7 -c -z -)' -i PKGBUILD"
  - "timeout 45m makepkg -s --noconfirm MAKEFLAGS='-j2' |ts -s '[%.T]'"
  - "ccache -s"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
- "CCACHE_DIR=\"$(pwd)/.ccache\" ccache -s"

deploy:
  on:
    branch: travis
  skip_cleanup: true
  provider: script
  script: bash .travis_deploy.sh
