sudo: required

branches:
  only:
#   - master
#   - devel
    - travis

cache:
  directories:
  - src
  - blender-addons-contrib.git
  - blender-addons.git
  - blender-dev-tools.git
  - blender-translations.git
  - blender

services:
- docker

arch:
# repos:
# - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
  # arch/aur packages
# - python
# - perl
  script:
  - "makepkg -s --noconfirm"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
- "ls"

deploy:
# file location $(cwd)/blender-2.8-git-2.8*.pkg.tar.xz
#- deploy.sh
